# Generated by Django 5.0.4 on 2024-06-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('stop_loss', models.BooleanField()),
                ('take_profit', models.BooleanField()),
                ('price', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
