# Generated by Django 5.0.4 on 2024-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conncted_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
