# Generated by Django 5.0.4 on 2024-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_history',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade_history',
            name='stop_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade_history',
            name='take_profit',
            field=models.FloatField(),
        ),
    ]
