# Generated by Django 5.0.4 on 2024-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_signals', '0002_conncted_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conncted_clients',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
