# Generated by Django 5.0.4 on 2024-06-06 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_signals', '0002_alter_trade_history_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
