# Generated by Django 5.0.4 on 2024-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_signals', '0003_alter_conncted_clients_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conncted_clients',
            name='count',
            field=models.BigIntegerField(),
        ),
    ]
