# Generated by Django 5.0.4 on 2024-05-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generate_signals', '0004_alter_conncted_clients_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conncted_Clients',
        ),
    ]
