# Generated by Django 5.0.4 on 2024-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='a5be3f28388445198aca24d452db1e50', max_length=64, primary_key=True, serialize=False),
        ),
    ]
