# Generated by Django 5.0.4 on 2024-06-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pair',
            field=models.CharField(blank=True, choices=[('EUR/USD', 'Euro/US Dollar'), ('USD/JPY', 'US Dollar/Japanese Yen'), ('GBP/USD', 'British Pound/US Dollar'), ('USD/CHF', 'US Dollar/Swiss Franc'), ('USD/CAD', 'US Dollar/Canadian Dollar'), ('AUD/USD', 'Australian Dollar/US Dollar'), ('NZD/USD', 'New Zealand Dollar/US Dollar'), ('EUR/GBP', 'Euro/British Pound'), ('EUR/JPY', 'Euro/Japanese Yen'), ('GBP/JPY', 'British Pound/Japanese Yen'), ('AUD/JPY', 'Australian Dollar/Japanese Yen'), ('NZD/JPY', 'New Zealand Dollar/Japanese Yen'), ('AUD/NZD', 'Australian Dollar/New Zealand Dollar'), ('AUD/CAD', 'Australian Dollar/Canadian Dollar'), ('GBP/AUD', 'British Pound/Australian Dollar'), ('GBP/CAD', 'British Pound/Canadian Dollar'), ('EUR/AUD', 'Euro/Australian Dollar'), ('USD/SGD', 'US Dollar/Singapore Dollar'), ('USD/HKD', 'US Dollar/Hong Kong Dollar'), ('USD/TRY', 'US Dollar/Turkish Lira'), ('USD/MXN', 'US Dollar/Mexican Peso'), ('USD/ZAR', 'US Dollar/South African Rand'), ('USD/SEK', 'US Dollar/Swedish Krona'), ('USD/DKK', 'US Dollar/Danish Krone'), ('USD/NOK', 'US Dollar/Norwegian Krone'), ('USD/INR', 'US Dollar/Indian Rupee'), ('USD/THB', 'US Dollar/Thai Baht'), ('EUR/CHF', 'Euro/Swiss Franc'), ('EUR/CAD', 'Euro/Canadian Dollar'), ('EUR/NZD', 'Euro/New Zealand Dollar'), ('GBP/CHF', 'British Pound/Swiss Franc'), ('CAD/JPY', 'Canadian Dollar/Japanese Yen'), ('NZD/CAD', 'New Zealand Dollar/Canadian Dollar'), ('XAU/USD', 'Gold/US Dollar'), ('XAG/USD', 'Silver/US Dollar'), ('XPT/USD', 'Platinum/US Dollar'), ('XPD/USD', 'Palladium/US Dollar')], max_length=100, verbose_name='Trading Pair'),
        ),
    ]
