# Generated by Django 5.0.4 on 2024-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0002_user_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_frame',
            field=models.CharField(blank=True, choices=[('1s', '1 Second'), ('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1mo', '1 Month')], max_length=50, verbose_name='Time Frame'),
        ),
    ]
