# Generated by Django 5.0.4 on 2024-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='f9c3ce6f255244fe9732250a84601e3f', max_length=64, primary_key=True, serialize=False),
        ),
    ]
