# Generated by Django 5.0.4 on 2024-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='3d8248167c5447f98a4d9671e9fbdc4d', max_length=64, primary_key=True, serialize=False),
        ),
    ]
