# Generated by Django 5.0.4 on 2024-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='6308e45071b84a74a6d325089c4cf604', max_length=64, primary_key=True, serialize=False),
        ),
    ]
