# Generated by Django 5.0.4 on 2024-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='131e789ddf8d441697de6cd5348f92ba', max_length=64, primary_key=True, serialize=False),
        ),
    ]
