# Generated by Django 5.0.4 on 2024-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0008_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='524b6d2fc1bc4560828692daf2100125', max_length=64, primary_key=True, serialize=False),
        ),
    ]
