# Generated by Django 5.0.4 on 2024-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0010_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='581830a281cb44f29ca7ecb4ed44aa8f', max_length=64, primary_key=True, serialize=False),
        ),
    ]
