# Generated by Django 5.0.5 on 2024-05-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_auth', '0011_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='d665f83cca6945e3acec08d53138b0f9', max_length=64, primary_key=True, serialize=False),
        ),
    ]
